name: TED Developer Docs

on:
  workflow_dispatch:
  push:
    branches: 
      - master
jobs:
  publish_site:
    name: "Build and publish site with Antora"
    runs-on: [ubuntu-latest]
    env:
      ACTIONS_ALLOW_UNSECURE_COMMANDS: 'true'
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Node.js for use with actions
        uses: actions/setup-node@v1.1.0
        with:
          version: 12.x

      - name: Install NPM
        run: npm install

      - name: Generate site
        run: gulp generate

      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@4.1.3
        with:
          # ACCESS_TOKEN: # optional
          GITHUB_TOKEN: "${{ github.token}}"
          FOLDER: build/site
          BRANCH: 'gh-pages'
          COMMIT_MESSAGE: "[CI] Publish Documentation for ${{ github.sha }}"
